### PR TITLE
Feature-166 pull from rides database

### PR DESCRIPTION
**Pull request by RVC13850**
#166

### CODE REVIEW

**Comment by RVC13850** [comment]
I think the edit and delete button functionality is out of scope because when I pull from rides I am using IDs to make it easier and I have changed my schema to incorporate that. So i think we should not do it until we finalize the schema for the database.

**Comment by CalvinVan** [comment]
> I think the edit and delete button functionality is out of scope because when I pull from rides I am using IDs to make it easier and I have changed my schema to incorporate that. So i think we should not do it until we finalize the schema for the database.

**Comment by devAgant** [comment]
> I think the edit and delete button functionality is out of scope because when I pull from rides I am using IDs to make it easier and I have changed my schema to incorporate that. So i think we should not do it until we finalize the schema for the database.

We don't have to push this ticket this sprint, it can carry over into next. As long as you moved it to the blocked column on the project board and had valid reason, its okay for tickets to rollover into next sprint due to blockage.

**Comment by devAgant** [comment]
Please close the PR if you do not want this ticket merged this sprint. Reopen it when the ticket is finished.

**Pull request closed without merging**
